# Generated by Django 4.2.7 on 2023-11-14 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tag_question_id_remove_tag_tag_id_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
