# Generated by Django 4.2.7 on 2023-11-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, to='app.question')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rates',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.rate'),
        ),
    ]
