# Generated by Django 4.2.7 on 2023-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_answers_count_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
