# Generated by Django 4.2.7 on 2023-11-14 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, to='app.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rates',
        ),
        migrations.AddField(
            model_name='answer',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='questionrate',
            name='user',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, to='app.profile'),
        ),
        migrations.AddField(
            model_name='answerrate',
            name='answer',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, to='app.answer'),
        ),
        migrations.AddField(
            model_name='answerrate',
            name='user',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, to='app.profile'),
        ),
    ]
