# Generated by Django 4.2.7 on 2023-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
