# Generated by Django 4.2.7 on 2023-11-14 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_question_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
